const projs = [
  {
    github: 'https://github.com/Dosx001/dosx001.github.io/',
    title: 'Dosx001.github.io',
    url: 'dosx001',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/VimTextEditor',
    title: 'Vim Text Editor',
    url: 'vimtexteditor',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/GI-Artifact-Leveler',
    title: 'Genshin Impact Artifact Leveler',
    url: 'genshinimpactartifactleveler',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/GitPrompt',
    title: 'Git Prompt',
    url: 'gitprompt',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/Dosx001/tree/main/resume',
    title: 'Resume',
    url: 'resume',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/vim-lazy',
    title: 'Vim Lazy',
    url: 'vimlazy',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/vim-template',
    title: 'Vim Template',
    url: 'vimtemplate',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/robinhood-bot',
    title: 'Robinhood Bot',
    url: 'robinhoodbot',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/anime-calendar',
    title: 'AnimeCalendar.github.io',
    url: 'animecalendar.github.io',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/aliasme',
    title: 'Aliasme',
    url: 'aliasme',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/Genshin_Tools',
    title: 'Genshin Tools',
    url: 'genshintools',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
    abandoned: <p>words</p>,
  },
  {
    github: 'https://github.com/Dosx001/mini-RPG',
    title: 'mini RPG',
    url: 'minirpg',
    what: <p>words</p>,
    why: <p>words</p>,
    how: <p>words</p>,
  },
];

export default projs;
